

AMD64_OBJECTS=\
 $(OBJ_PATH)\$O\ncdriver.obj \
 $(OBJ_PATH)\$O\utils.obj \
 $(OBJ_PATH)\$O\callbacks.obj \
 $(OBJ_PATH)\$O\link.obj \
 $(OBJ_PATH)\$O\unload.obj \
 $(OBJ_PATH)\$O\mj_create.obj \
 $(OBJ_PATH)\$O\mj_close.obj \
 $(OBJ_PATH)\$O\mj_device_control.obj \
 $(OBJ_PATH)\$O\mj_shutdown.obj \
 $(OBJ_PATH)\$O\globals.obj \





# lowercased
BASEDIR=c:\winddk\7600.16385.1
OBJECT_ROOT=c:\winddk\7600.16385.1
MAKEDIR_LOWERCASE=c:\users\administrator\documents\nocheat\nocheat\nocheatdriverv2
OBJ_PATH=c:\users\administrator\documents\nocheat\nocheat\nocheatdriverv2
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
